on:
  workflow_call:
    inputs:
      registry-name:
        type: string
        required: true
        description: 'The name of the registry to push to'
      image-name:
        type: string
        required: true
        description: 'The name of the image to push'
      image-tag:
        type: string
        required: true
        description: 'The tag of the image to push'
      build-args:
        type: string
        required: false
        description: 'The build args to pass to the build'
      context:
        type: string
        required: false
        description: 'The path to the dockerfile'
        default: '.'
      file:
        type: string
        required: false
        description: 'The name of the dockerfile'
      recursive-submodule-checkout:
        type: boolean
        required: false
        description: 'Whether to pass the `submodules: recursive` option and PAT to the checkout step'
        default: false
      submodules-app-id:
        type: string
        required: false
        description: 'The id of the app used for authentication. Only needed if `recursive-submodule-checkout` is true.'
        default: '213843'
      submodules-app-installation-id:
        type: string
        required: false
        description: 'The installation id of the app used for authentication. Only needed if `recursive-submodule-checkout` is true.'
        default: '26790862'
    secrets:
      registry-username:
        required: true
        description: 'The username on the registry'
      registry-password:
        required: true
        description: 'The password on the registry'
      submodules-app-private-key:
        required: false
        description: 'The private-key of the app used for authentication. Only needed if `recursive-submodule-checkout` is true'

jobs:
  build-push:
    runs-on: [self-hosted, m2c1-runner]
    steps:
      - if: ${{ !inputs.recursive-submodule-checkout }}
        name: Checkout without submodules
        uses: actions/checkout@v4
      # The following steps are only needed for recursive submodules checkout
      - name: '[SUBMODULES] Obtain GitHub App Installation Access Token'
        uses: Nastaliss/get-github-app-pat@v1
        id: githubAppAuth
        with:
          app-id: ${{ inputs.submodules-app-id }}
          app-installation-id: ${{ inputs.submodules-app-installation-id }}
          app-private-key: ${{ secrets.submodules-app-private-key }}
      - if: ${{ inputs.recursive-submodule-checkout }}
        name: '[SUBMODULES] Checkout with submodules'
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ steps.githubAppAuth.outputs.access-token }}
      # The previous steps are only needed for recursive submodules checkout
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Azure Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.registry-name }}/${{inputs.image-name}}:${{inputs.image-tag}}
          cache-from: type=registry,ref=${{ inputs.registry-name }}/${{inputs.image-name}}:buildcache
          cache-to: type=registry,mode=max,ref=${{ inputs.registry-name }}/${{inputs.image-name}}:buildcache
          context: ${{ inputs.context }} # https://github.com/docker/build-push-action/issues/638 / https://github.com/docker/build-push-action/issues/300#issuecomment-1268406727
          build-args: ${{ inputs.build-args }}
          file: ${{ inputs.file }}
