on:
  workflow_call:
    inputs:
      registry-name:
        type: string
        required: true
        description: 'The name of the registry to push to'
      image-name:
        type: string
        required: true
        description: 'The name of the image to push'
      image-tag:
        type: string
        required: true
        description: 'The tag of the image to push'
      build-args:
        type: string
        required: false
        description: 'The build args to pass to the build'
    secrets:
      registry-username:
        required: true
        description: 'The username on the registry'
      registry-password:
        required: true
        description: 'The password on the registry'

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Azure Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registry-name }}/${{inputs.image-name}}:${{inputs.image-tag}}
          context: . # https://github.com/docker/build-push-action/issues/638 / https://github.com/docker/build-push-action/issues/300#issuecomment-1268406727
          build-args: ${{ toJSON(inputs.build-args) }} # Input is most likely a multiline string, so we need to convert it to JSON to preserve the newlines
