on:
  workflow_call:
    inputs:
      registry-name:
        type: string
        required: true
        description: 'The name of the registry to push to'
      image-name:
        type: string
        required: true
        description: 'The name of the image to push'
      image-tag:
        type: string
        required: true
        description: 'The tag of the image to push'
      build-args:
        type: string
        required: false
        description: 'The build args to pass to the build'
      context:
        type: string
        required: false
        description: 'The path to the dockerfile'
        default: "."
      file:
        type: string
        required: false
        description: 'The name of the dockerfile'
      recursive-submodule-checkout:
        type: boolean
        required: false
        description: 'Whether to pass the `submodules: recursive` option and PAT to the checkout step'
        default: false
    secrets:
      registry-username:
        required: true
        description: 'The username on the registry'
      registry-password:
        required: true
        description: 'The password on the registry'
      submodules-app-credentials-token:
        required: false
        description: 'The app-credentials-token. Only needed if `recursive-submodule-checkout` is true. To generate one, see https://dev.to/dtinth/authenticating-as-a-github-app-in-a-github-actions-workflow-27co'

jobs:
  build-push:
    runs-on: [self-hosted, default-runner]
    steps:
      - if: ${{ !inputs.recursive-submodule-checkout }}
        name: Checkout without submodules
        uses: actions/checkout@v3
      # https://dev.to/dtinth/authenticating-as-a-github-app-in-a-github-actions-workflow-27co
      - uses: actions/setup-node@v3
        if: ${{ inputs.recursive-submodule-checkout }}
      - run: npm install -g npx
        if: ${{ inputs.recursive-submodule-checkout }}
      - name: Obtain GitHub App Installation Access Token
        if: ${{ inputs.recursive-submodule-checkout }}
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.submodules-app-credentials-token }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Use the obtained token
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - if: ${{ inputs.recursive-submodule-checkout }}
        name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ steps.githubAppAuth.outputs.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Azure Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registry-name }}/${{inputs.image-name}}:${{inputs.image-tag}}
          cache-from: type=registry,ref=${{ inputs.registry-name }}/${{inputs.image-name}}:buildcache
          cache-to: type=registry,mode=max,ref=${{ inputs.registry-name }}/${{inputs.image-name}}:buildcache
          context: ${{ inputs.context }} # https://github.com/docker/build-push-action/issues/638 / https://github.com/docker/build-push-action/issues/300#issuecomment-1268406727
          build-args: ${{ inputs.build-args }}
          file: ${{ inputs.file }}
