on:
  workflow_call:
    inputs:
      registry-name:
        type: string
        required: true
        description: 'The name of the registry to push to'
      registry-username:
        type: string
        required: true
        description: 'The username on the registry'
      image-name:
        type: string
        required: true
        description: 'The name of the image to push'
      image-tag:
        type: string
        required: true
        description: 'The tag of the image to push'
    secrets:
      registry-password:
        required: true
        description: 'The password on the registry'

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Azure Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registry-name }}/${{image-name}}:${{image-tag}}
