on:
  workflow_call:
    inputs:
      refs-suffixes:
        description: 'Comma-separated list of refs suffixes to delete'
        type: string
        required: false
        default: "_deploy,_deploy-fast"

jobs:
  delete-tag:
    runs-on: [self-hosted, default-runner]
    steps:
      - name: Delete ref deploy
        uses: actions/github-script@v5
        with:
          script: |
            const refsToDelete = "${{ inputs.refs-suffixes }}".split(",").map(ref => `tags/${{ github.event.ref }}${ref.trim()}`);
            for (const ref of refsToDelete) {
              try {
                console.log(`Getting ref ${ref}`);
                await github.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref
                });
                console.log("Found ref, deleting it...");
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref
                });
                console.log("Done !");
              } catch (error) {
                console.log(error);
                if (error.status === 404) {
                  console.log(`No tag ${ref} found, skipping`);
                  continue;
                }
                throw error;
              }
            }
