on:
  workflow_call:
jobs:
  build-push:
    runs-on: [self-hosted, m1c1-runner]
    steps:
      - uses: actions/checkout@v4
      - name: Tag deploy fast
        run: |
          git tag -f "${{ github.ref_name }}_deploy-fast" HEAD
          git push -f origin "${{ github.ref_name }}_deploy-fast"
