on:
  workflow_call:
jobs:
  build-push:
    runs-on: [self-hosted, tiny-runner]
    steps:
      - uses: actions/checkout@v4
      - name: Tag deploy
        run: |
          git tag -f "${{ github.ref_name }}_deploy" HEAD
          git push -f origin "${{ github.ref_name }}_deploy"
